### ISSUE TITLE
ISSUE: With big files the values on the left are inaccurate. 

### ISSUE THREAD

**Issue by DexrnZacAttack** [DexrnZacAttack/iCUETempGraphTool#2]
They are also jumbled

![CPU_Package](https://github.com/DexrnZacAttack/iCUETempGraphTool/assets/60078656/6b3785b3-af00-4b43-991f-61663d0fec7b)

**Comment by DexrnZacAttack** [comment]
note this picture was taken using an old build but it still seems to apply

**Comment by DexrnZacAttack** [comment]
![image](https://github.com/DexrnZacAttack/iCUETempGraphTool/assets/60078656/e349ef71-a66f-4812-aaf7-a582ede7fb8e)

This one was taken on my MacBook

**Comment by DexrnZacAttack** [comment]
Fixed

**Comment by CarPBon** [comment]
very nice
